-- MySQL Script generated by MySQL Workbench
-- 01/02/17 18:07:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CAT_DOMINIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAT_DOMINIO` (
  `Id` DECIMAL(10,0) NOT NULL,
  `Descripcion` VARCHAR(2000) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAT_PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAT_PROVEEDOR` (
  `Id` DECIMAL(10,0) NOT NULL,
  `Descripcion` VARCHAR(2000) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAT_PLATAFORMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAT_PLATAFORMA` (
  `Id` DECIMAL(10,0) NOT NULL,
  `Descripcion` VARCHAR(2000) NULL,
  `Comentarios` VARCHAR(2000) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`APLICACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`APLICACION` (
  `CSI_ID` INT NOT NULL,
  `Id_Dominio` DECIMAL(10,0) NULL,
  `PTB_ID` VARCHAR(45) NULL,
  `DescripcionCorta` VARCHAR(200) NULL,
  `DescripcionLarga` VARCHAR(2000) NULL,
  `Id_L1` DECIMAL(10,0) NULL,
  `Id_L2` DECIMAL(10,0) NULL,
  `Id_L3` DECIMAL(10,0) NULL,
  `Id_Plat1` DECIMAL(10,0) NULL,
  `Id_Plat2` DECIMAL(10,0) NULL,
  `Id_Plat3` DECIMAL(10,0) NULL,
  `Comentarios` VARCHAR(2000) NULL,
  `Contactos Proveedor_Proveedor` INT NOT NULL,
  PRIMARY KEY (`CSI_ID`),
  INDEX `fk_CatDominio_Aplicacion_idx` (`Id_Dominio` ASC),
  INDEX `fk_CatProveedor_Aplicacion_idx` (`Id_L1` ASC),
  INDEX `fk_CatProveedor_Aplicacion_idx1` (`Id_L2` ASC),
  INDEX `fk_CatProveedor_Aplicacion_L3_idx` (`Id_L3` ASC),
  INDEX `fk_CatPlataforma_Aplicacion_Id_Plat1_idx` (`Id_Plat1` ASC),
  INDEX `fk_CatPlataforma_Aplicacion_Id_Plat2_idx` (`Id_Plat2` ASC),
  INDEX `fk_CatPlataforma_Aplicacion_Id_Plat3_idx` (`Id_Plat3` ASC),
  CONSTRAINT `fk_CAT_DOMINIO_APLICACION`
    FOREIGN KEY (`Id_Dominio`)
    REFERENCES `mydb`.`CAT_DOMINIO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PROVEEDOR_APICACION_Id_L1`
    FOREIGN KEY (`Id_L1`)
    REFERENCES `mydb`.`CAT_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PROVEEDOR_APICACION_Id_L2`
    FOREIGN KEY (`Id_L2`)
    REFERENCES `mydb`.`CAT_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PROVEEDOR_APICACION_Id_L3`
    FOREIGN KEY (`Id_L3`)
    REFERENCES `mydb`.`CAT_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PLATAFORMA_APLICACION_Id_Plat1`
    FOREIGN KEY (`Id_Plat1`)
    REFERENCES `mydb`.`CAT_PLATAFORMA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PLATAFORMA_APLICACION_Id_Plat2`
    FOREIGN KEY (`Id_Plat2`)
    REFERENCES `mydb`.`CAT_PLATAFORMA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fk_CAT_PROVEEDOR_APICACION_Id_Plat3`
    FOREIGN KEY (`Id_Plat3`)
    REFERENCES `mydb`.`CAT_PLATAFORMA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dominios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dominios` (
  `Id` INT NULL,
  `Descripción` VARCHAR(100) NULL,
  `` VARCHAR(45) NULL,
  `Middleware` VARCHAR(45) NULL,
  `` VARCHAR(45) NULL,
  `` VARCHAR(45) NULL,
  `` INT NOT NULL,
  `Dominioscol` VARCHAR(45) NULL,
  INDEX `fk_Dominios_Aplicaciones por Dominios_idx` (`` ASC),
  CONSTRAINT `fk_Dominios_Aplicaciones por Dominios`
    FOREIGN KEY (``)
    REFERENCES `mydb`.`APLICACION` (`CSI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAT_PUESTOCITI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAT_PUESTOCITI` (
  `Id` DECIMAL(10,0) NOT NULL,
  `Descripcion` VARCHAR(2000) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAT_PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAT_PAIS` (
  `Id` DECIMAL(10,0) NOT NULL,
  `Descripcion` VARCHAR(2000) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAT_CIUDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAT_CIUDAD` (
  `Id` DECIMAL(10,0) NOT NULL,
  `Id_Pais` DECIMAL(10,0) NULL,
  `Descripcion` VARCHAR(2000) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_CatPais_CatCiudad_idx` (`Id_Pais` ASC),
  CONSTRAINT `fk_CAT_PAIS_CAT_CIUDAD`
    FOREIGN KEY (`Id_Pais`)
    REFERENCES `mydb`.`CAT_PAIS` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RECURSO_CITI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RECURSO_CITI` (
  `SOE_ID` VARCHAR(7) NOT NULL,
  `ApellidoPaterno` VARCHAR(45) NULL,
  `ApellidoMaterno` VARCHAR(45) NULL,
  `PrimerNombre` VARCHAR(45) NULL,
  `SegundoNombre` VARCHAR(45) NULL,
  `Id_Dominio` DECIMAL(10,0) NULL,
  `Id_Puesto` DECIMAL(10,0) NULL,
  `Id_Ciudad` DECIMAL(10,0) NULL,
  `Ext` VARCHAR(10) NULL,
  `Movil` VARCHAR(10) NULL,
  `Telefono` VARCHAR(10) NULL,
  `Email` VARCHAR(60) NULL,
  `Id_ReportaA` VARCHAR(7) NULL,
  `Id_CSIs` VARCHAR(2000) NULL,
  `Comentarios` VARCHAR(2000) NULL,
  PRIMARY KEY (`SOE_ID`),
  INDEX `fk_CatDominio_RecursoCiti_Dominio_idx` (`Id_Dominio` ASC),
  INDEX `fk_CatpuestoCiti_IdPuesto_idx` (`Id_Puesto` ASC),
  INDEX `fk_CatCiudad_Id_Ciudad_idx` (`Id_Ciudad` ASC),
  INDEX `fk_RecursoCiti_RecursoCiti_idx` (`Id_ReportaA` ASC),
  CONSTRAINT `fk_CAT_DOMINIO_RECURSO_CITI`
    FOREIGN KEY (`Id_Dominio`)
    REFERENCES `mydb`.`CAT_DOMINIO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PUESTOCITI_RECURSO_CITI`
    FOREIGN KEY (`Id_Puesto`)
    REFERENCES `mydb`.`CAT_PUESTOCITI` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_CIUDAD_RECURSO_CITI`
    FOREIGN KEY (`Id_Ciudad`)
    REFERENCES `mydb`.`CAT_CIUDAD` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_CITIi_RECURSO_CITI`
    FOREIGN KEY (`Id_ReportaA`)
    REFERENCES `mydb`.`RECURSO_CITI` (`SOE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta Personal CityBanamex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulta Personal CityBanamex` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAT_PUESTO_PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAT_PUESTO_PROVEEDOR` (
  `Id` DECIMAL(10,0) NOT NULL,
  `Descripcion` VARCHAR(2000) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RecursoCity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RecursoCity` (
  `SOE_ID` INT NOT NULL,
  `ApellidoPaterno` VARCHAR(45) NULL,
  `ApellidoMaterno` VARCHAR(45) NULL,
  `RecursoCitycol` VARCHAR(45) NULL,
  PRIMARY KEY (`SOE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RECURSO_PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RECURSO_PROVEEDOR` (
  `Id` DECIMAL(10,0) NOT NULL,
  `Id_Proveedor` DECIMAL(10,0) NOT NULL,
  `NumeroEmpleado` DECIMAL(10,0) NOT NULL,
  `ClaveEmpleado` DECIMAL(10,0) NOT NULL,
  `ApellidoPaterno` VARCHAR(45) NULL,
  `ApellidoMaterno` VARCHAR(45) NULL,
  `PrimerNombre` VARCHAR(45) NULL,
  `SegundoNombre` VARCHAR(45) NULL,
  `Id_Ciudad` DECIMAL(10,0) NULL,
  `Movil_Personal` VARCHAR(10) NULL,
  `Telefono_Particular` VARCHAR(10) NULL,
  `Email_Personal` VARCHAR(60) NULL,
  `Id_Puesto` DECIMAL(10,0) NULL,
  `Id_Reporta_A` DECIMAL(10,0) NULL,
  `Telefono_Proveedor` VARCHAR(10) NULL,
  `Ext_Proveedor` VARCHAR(10) NULL,
  `Email_Proveedor` VARCHAR(60) NULL,
  `SOE_ID` VARCHAR(7) NULL,
  `Ext_Citi` VARCHAR(10) NULL,
  `Email_Citi` VARCHAR(60) NULL,
  `Id_CSIs` VARCHAR(2000) NULL,
  `Comentarios` VARCHAR(2000) NULL,
  INDEX `fk_CAT_PROVEEDOR_RECURSOS_PROVEEDOR_idx` (`Id_Proveedor` ASC),
  INDEX `fk_CAT_CIUDAD_RECURSOS_PROVEEDOR_idx` (`Id_Ciudad` ASC),
  INDEX `fk_CAT_PUESTO_PROVEEDOR_RECURSOS_PROVEEDOR_idx` (`Id_Puesto` ASC),
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `NumeroEmpleado_UNIQUE` (`NumeroEmpleado` ASC),
  CONSTRAINT `fk_CAT_PROVEEDOR_RECURSO_PROVEEDOR`
    FOREIGN KEY (`Id_Proveedor`)
    REFERENCES `mydb`.`CAT_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_CIUDAD_RECURSO_PROVEEDOR`
    FOREIGN KEY (`Id_Ciudad`)
    REFERENCES `mydb`.`CAT_CIUDAD` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PUESTO_PROVEEDOR_RECURSO_PROVEEDOR`
    FOREIGN KEY (`Id_Puesto`)
    REFERENCES `mydb`.`CAT_PUESTO_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAT_PERFIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAT_PERFIL` (
  `Id_Perfil` DECIMAL(10,0) NOT NULL,
  `Descripcion` VARCHAR(2000) NULL,
  PRIMARY KEY (`Id_Perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `Id_Usuarios` DECIMAL(10,0) NOT NULL,
  `Id_Proveedor` DECIMAL(10,0) NULL,
  `Email` VARCHAR(60) NULL,
  `PrimerNombre` VARCHAR(45) NULL,
  `SegundoNombe` VARCHAR(45) NULL,
  `ApellidoPaterno` VARCHAR(45) NULL,
  `ApellidoMaterno` VARCHAR(45) NULL,
  `Clave` VARCHAR(45) NULL,
  `Id_Perfil` DECIMAL(10,0) NULL,
  `Activo` TINYINT(1) NULL,
  PRIMARY KEY (`Id_Usuarios`),
  INDEX `fk_CAT_PROVEEDOR_USUARIO_idx` (`Id_Proveedor` ASC),
  INDEX `fk_CAT_PERFIL_USUARIO_idx` (`Id_Perfil` ASC),
  CONSTRAINT `fk_CAT_PROVEEDOR_USUARIO`
    FOREIGN KEY (`Id_Proveedor`)
    REFERENCES `mydb`.`CAT_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PERFIL_USUARIO`
    FOREIGN KEY (`Id_Perfil`)
    REFERENCES `mydb`.`CAT_PERFIL` (`Id_Perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`APLICACION_PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`APLICACION_PROVEEDOR` (
  `Id_Proveedor` DECIMAL(10,0) NOT NULL,
  `CSI_ID` INT NULL,
  `L1_Primario` DECIMAL(10,0) NULL,
  `L1_Backup` DECIMAL(10,0) NULL,
  `L2_Primario` DECIMAL(10,0) NULL,
  `L2_Backup` DECIMAL(10,0) NULL,
  `L3_Primario` DECIMAL(10,0) NULL,
  `L3_Backup` DECIMAL(10,0) NULL,
  PRIMARY KEY (`Id_Proveedor`),
  INDEX `fk_APLICACION_APLICACION_PROVEEDOR_idx` (`CSI_ID` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_idx` (`L1_Primario` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_1_idx` (`L1_Backup` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_2_idx` (`L2_Primario` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_3_idx` (`L2_Backup` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_4_idx` (`L3_Primario` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_5_idx` (`L3_Backup` ASC),
  CONSTRAINT `fk_CAT_PROVEEDOR_APLICACION_PROVEEDOR`
    FOREIGN KEY (`Id_Proveedor`)
    REFERENCES `mydb`.`CAT_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_APLICACION_APLICACION_PROVEEDOR`
    FOREIGN KEY (`CSI_ID`)
    REFERENCES `mydb`.`APLICACION` (`CSI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR`
    FOREIGN KEY (`L1_Primario`)
    REFERENCES `mydb`.`RECURSO_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_1`
    FOREIGN KEY (`L1_Backup`)
    REFERENCES `mydb`.`RECURSO_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_2`
    FOREIGN KEY (`L2_Primario`)
    REFERENCES `mydb`.`RECURSO_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_3`
    FOREIGN KEY (`L2_Backup`)
    REFERENCES `mydb`.`RECURSO_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_4`
    FOREIGN KEY (`L3_Primario`)
    REFERENCES `mydb`.`RECURSO_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_5`
    FOREIGN KEY (`L3_Backup`)
    REFERENCES `mydb`.`RECURSO_PROVEEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
